package com.cong.entity;

import java.io.Serializable;
import java.util.Date;

public class BaseEntity implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base.id
     *
     * @mbg.generated Sat Sep 23 10:27:35 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base.create_by
     *
     * @mbg.generated Sat Sep 23 10:27:35 CST 2017
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base.update_by
     *
     * @mbg.generated Sat Sep 23 10:27:35 CST 2017
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base.create_time
     *
     * @mbg.generated Sat Sep 23 10:27:35 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base.update_time
     *
     * @mbg.generated Sat Sep 23 10:27:35 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base.dele_flag
     *
     * @mbg.generated Sat Sep 23 10:27:35 CST 2017
     */
    private String deleFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base.id
     *
     * @return the value of t_base.id
     *
     * @mbg.generated Sat Sep 23 10:27:35 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base.id
     *
     * @param id the value for t_base.id
     *
     * @mbg.generated Sat Sep 23 10:27:35 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base.create_by
     *
     * @return the value of t_base.create_by
     *
     * @mbg.generated Sat Sep 23 10:27:35 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base.create_by
     *
     * @param createBy the value for t_base.create_by
     *
     * @mbg.generated Sat Sep 23 10:27:35 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base.update_by
     *
     * @return the value of t_base.update_by
     *
     * @mbg.generated Sat Sep 23 10:27:35 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base.update_by
     *
     * @param updateBy the value for t_base.update_by
     *
     * @mbg.generated Sat Sep 23 10:27:35 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base.create_time
     *
     * @return the value of t_base.create_time
     *
     * @mbg.generated Sat Sep 23 10:27:35 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base.create_time
     *
     * @param createTime the value for t_base.create_time
     *
     * @mbg.generated Sat Sep 23 10:27:35 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base.update_time
     *
     * @return the value of t_base.update_time
     *
     * @mbg.generated Sat Sep 23 10:27:35 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base.update_time
     *
     * @param updateTime the value for t_base.update_time
     *
     * @mbg.generated Sat Sep 23 10:27:35 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base.dele_flag
     *
     * @return the value of t_base.dele_flag
     *
     * @mbg.generated Sat Sep 23 10:27:35 CST 2017
     */
    public String getDeleFlag() {
        return deleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base.dele_flag
     *
     * @param deleFlag the value for t_base.dele_flag
     *
     * @mbg.generated Sat Sep 23 10:27:35 CST 2017
     */
    public void setDeleFlag(String deleFlag) {
        this.deleFlag = deleFlag == null ? null : deleFlag.trim();
    }
}